base_config:
  - ./diffsr_base.yaml
  - ./df2k4x.yaml
trainer_cls: tasks.srdiff.SRDiffTrainer

# model
unet_dim_mults: 1|2|3|4
decay_steps: 100000
hidden_size: 64
rrdb_num_feat: 32
rrdb_num_block: 8

# added by @hubert
save_intermediate: false
test_diff: true

# train and test
batch_size: 10
max_updates: 400000
eval_batch_size: 10
test_batch_size: 1
train_diffsr: true
val_check_interval: 75000
save_ckpt_interval: 25000
train_diffsr: true
max_s2_images: 8
use_highresnet_ltae: false
use_rrdb_ltae: true
misr_ref_image: closest
misr: true
sr_scale: 6.25
