base_config:
  - ../sr_base.yaml
  - ../df2k4x.yaml
trainer_cls: tasks.highresnet_ltae.HighResNetLTAETrainer
# model
hidden_size: 64
lr: 0.0007
num_block: 17

# train and eval
max_updates: 400000
batch_size: 32
eval_batch_size: 32
test_batch_size: 1
val_check_interval: 50000
save_ckpt_interval: 40000
train_diffsr: false
max_s2_images: 8
misr_ref_image: closest
